/**
 * Agent BUILDER — the agent can build and host websites and mini web apps.
 *
 * This is the capability that turns the assistant from "talks about work"
 * into "produces finished products":
 *
 *   • build_website  — a complete, branded, single-file HTML site/web app
 *     is generated by Sarvam (with a deterministic signature builder as
 *     the always-works fallback), stored in R2 and served from a public
 *     URL:  https://<worker>/sites/<id>
 *   • save_note      — research summaries, strategy notes, plans and
 *     reports are stored as artifacts; they are viewable in the app AND
 *     served as a clean shareable page at /sites/<id>.
 *   • list_artifacts — everything the agent has built for this user.
 *
 * Safety model: artifacts are STATIC files (no server execution). The AI's
 * HTML passes a light sanitizer that removes remote <script src>, iframes
 * and remote stylesheets (inline scripts survive — mini web apps need
 * them, and they only ever run inside the artifact's own page).
 */

import { sarvamChat } from './sarvam.js';
import { getBusinessProfile, brandFor, profileToFacts } from './business.js';

const SITE_KINDS = ['landing', 'promo', 'event', 'portfolio', 'webapp', 'report'];
const ARTIFACT_LIST_CAP = 60;
const MAX_SITE_BYTES = 400_000;

const KIND_GUIDE = {
  landing: 'a marketing landing page: hero with a strong promise, 3-4 benefit cards, social-proof strip, clear CTA, FAQ or contact footer',
  promo: 'a high-urgency offer page: big discount hook, offer card, what-you-get list, countdown-feel banner (static, no fake timers), terms line, CTA',
  event: 'an event/invite page: date-time-venue hero, agenda timeline, speakers/guests chips, RSVP button (mailto RSVP), map-link footer',
  portfolio: 'a classy portfolio: intro, work-grid cards (gradients/emoji art, no external images), skills row, testimonial quote, contact CTA',
  webapp: 'a SMALL INTERACTIVE single-page app that feels native on a phone: bottom tab bar, cards, forms persisted in localStorage, a genuinely useful core interaction (calculator, tracker, checklist, quiz, notes...). Inline <script> is allowed and expected — but the app must work offline in one file',
  report: 'a clean research/report one-pager: title header, key-findings cards, a findings table, sources list with links, date stamp',
};

function siteSystemPrompt(brand, kind) {
  const facts = profileToFacts(brand.profile || {}).facts || {};
  const factLine = Object.entries(facts)
    .slice(0, 8)
    .map(([k, v]) => `${k}: ${Array.isArray(v) ? v.join(', ') : v}`)
    .join(' | ');
  return `You are an elite web designer and front-end engineer. Produce ONE complete, production-quality, SINGLE-FILE HTML page.

KIND: ${kind} — build ${KIND_GUIDE[kind] || KIND_GUIDE.landing}.

HARD RULES:
- ONE self-contained HTML document. ALL CSS inline in a <style> tag. No external CSS, JS, fonts, CDNs, iframes or image URLs — visuals come from typography, gradients, SVG and emoji only.
- Mobile-first, responsive, fast. System font stack.
- Premium visual standard: strong hero, generous spacing, consistent radius/shadows, accessible contrast, subtle hover/active states.
- Business branding: brand color ${brand.color}, name "${brand.name}"${factLine ? `; facts: ${factLine}` : ''}.
- Copy must be specific to the brief — no lorem ipsum, no placeholder brackets left behind.
${kind === 'webapp' ? '- Inline <script> is allowed for the app logic; persist state in localStorage; no network calls.' : '- No JavaScript, or a tiny inline script for minor polish only.'}
- Output the raw HTML document ONLY — start with <!DOCTYPE html>, no markdown fences, no commentary.`;
}

/* ── Light sanitizer: block remote code/data surfaces, keep the page ── */

function sanitizeSiteHtml(html) {
  return String(html)
    // Remote-src scripts are removed WHOLE (tag + content + closing tag);
    // inline scripts survive — mini web apps need them, and they only ever
    // run inside the artifact's own page.
    .replace(/<script[^>]*\ssrc\s*=\s*['"]?(https?:)?\/\/[^>]*>[\s\S]*?<\/script\s*>/gi, '')
    .replace(/<script[^>]*\ssrc\s*=\s*['"]?(https?:)?\/\/[^>]*>/gi, '')
    .replace(/<iframe[\s\S]*?<\/iframe\s*>/gi, '')
    .replace(/<iframe[^>]*>/gi, '')
    .replace(/<link[^>]*\shref\s*=\s*['"]?(https?:)?\/\/[^>]*>/gi, '');
}

/* ── Deterministic signature site (always works, on-brand) ────────── */

function esc(s) {
  return String(s || '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/** Split the brief into sentence-ish feature bullets for the fallback. */
function briefParts(brief) {
  const parts = String(brief || '')
    .split(/(?:\.\s*|\n+|;\s*)/)
    .map((s) => s.trim())
    .filter((s) => s.length > 8)
    .slice(0, 4);
  return parts.length ? parts : ['Built by your CRM AI assistant'];
}

function signatureSite(args, brand, kind) {
  const title = esc(args.title || `${brand.name} — ${kind}`);
  const color = /^#[0-9a-fA-F]{6}$/.test(brand.color || '') ? brand.color : '#6C8CFF';
  const tagline = esc(String(args.brief || '').split(/(?:\.\s*|\n)/)[0] || `Made with ${brand.name}`);
  const features = briefParts(args.brief).map(
    (f, i) => `<div class="card"><div class="ico">${['✦', '◆', '●', '▲'][i % 4]}</div><p>${esc(f)}</p></div>`
  ).join('');
  const cta = esc(args.cta_text || 'Get in touch');
  const ctaHref = args.cta_url ? esc(args.cta_url) : (brand.ctaUrl ? esc(brand.ctaUrl) : `mailto:${esc(args.contact_email || brand.contactEmail || 'hello@example.com')}`);
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="${color}">
<title>${title}</title>
<style>
:root{--brand:${color};--ink:#0f1222;--mut:#5c6178}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,sans-serif;color:var(--ink);background:#f6f7fb;line-height:1.6}
.hero{background:linear-gradient(135deg,var(--brand),color-mix(in srgb,var(--brand) 55%, #101223));color:#fff;padding:72px 20px 64px;text-align:center}
.hero .kicker{display:inline-block;font-size:12px;letter-spacing:.18em;text-transform:uppercase;opacity:.85;margin-bottom:14px}
.hero h1{font-size:clamp(28px,6vw,44px);line-height:1.15;max-width:720px;margin:0 auto 14px;font-weight:800}
.hero p{max-width:560px;margin:0 auto 26px;font-size:17px;opacity:.94}
.btn{display:inline-block;background:#fff;color:var(--ink);font-weight:700;padding:14px 28px;border-radius:999px;text-decoration:none;box-shadow:0 10px 30px rgba(0,0,0,.25)}
.wrap{max-width:960px;margin:0 auto;padding:48px 20px}
h2{font-size:22px;margin-bottom:18px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}
.card{background:#fff;border-radius:16px;padding:20px;box-shadow:0 6px 24px rgba(15,18,34,.07);border:1px solid rgba(15,18,34,.05)}
.card .ico{width:38px;height:38px;border-radius:12px;background:color-mix(in srgb,var(--brand) 16%, #fff);color:var(--brand);display:grid;place-items:center;font-size:18px;margin-bottom:10px}
.cta-band{background:var(--ink);color:#fff;border-radius:20px;padding:34px 24px;text-align:center;margin:20px}
.cta-band .btn{background:var(--brand);color:#fff}
footer{padding:26px 20px 40px;text-align:center;color:var(--mut);font-size:13px}
</style></head><body>
<div class="hero">
  <span class="kicker">${esc(brand.name)}</span>
  <h1>${title}</h1>
  <p>${tagline}</p>
  <a class="btn" href="${ctaHref}">${cta}</a>
</div>
<div class="wrap"><h2>Highlights</h2><div class="grid">${features}</div></div>
<div class="cta-band"><h2 style="color:#fff">Ready when you are</h2>
<p style="opacity:.85;margin:8px 0 18px">${tagline}</p>
<a class="btn" href="${ctaHref}">${cta}</a></div>
<footer>© ${new Date().getFullYear()} ${esc(brand.name)} · Built by the ${esc(brand.name)} AI agent</footer>
</body></html>`;
}

/* ── Artifact registry (per-user, in the state store) ─────────────── */

async function artifactList(store, uid) {
  if (!store || !uid) return [];
  return safeArr(await store.get(`agent:artifacts:${uid}`));
}

function safeArr(raw) {
  try {
    const v = JSON.parse(raw);
    return Array.isArray(v) ? v : [];
  } catch {
    return [];
  }
}

async function putArtifact(store, uid, meta) {
  if (!store || !uid) return;
  const list = await artifactList(store, uid);
  list.unshift(meta);
  await store.put(`agent:artifacts:${uid}`, JSON.stringify(list.slice(0, ARTIFACT_LIST_CAP)));
}

export async function listArtifacts(store, uid, limit = 20) {
  const list = await artifactList(store, uid);
  return list.slice(0, Math.min(Number(limit) || 20, 40));
}

export async function getArtifactDoc(store, uid, id) {
  const list = await artifactList(store, uid);
  return list.find((a) => a.id === id) || null;
}

/** Save a note/report artifact (markdown-ish text, shareable page). */
export async function saveNote(store, user, args) {
  const uid = user?.uid || '';
  const title = String(args.title || '').trim().slice(0, 140) || 'Untitled note';
  const content = String(args.content || '').trim().slice(0, 40000);
  if (content.length < 10) return { ok: false, error: 'note content is too short' };
  const id = `n_${Date.now().toString(36)}${Math.floor(Math.random() * 46656).toString(36)}`;
  const doc = { id, uid, kind: 'note', title, content, at: new Date().toISOString() };
  if (store) await store.put(`agent:artifact:${id}`, JSON.stringify(doc));
  await putArtifact(store, uid, { id, kind: 'note', title, at: doc.at, by: user?.displayName || 'agent' });
  return { ok: true, artifact_id: id, kind: 'note', title, note: `saved "${title}" — viewable in the app and shareable as a page` };
}

/** Minimal markdown-ish rendering for note artifacts (safe: escaped). */
function noteToHtml(doc) {
  const body = String(doc.content || '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .split(/\n{2,}/)
    .map((p) => {
      const lines = p.split('\n').map((l) => {
        if (/^#{1,3}\s/.test(l)) return `<h2>${l.replace(/^#{1,3}\s/, '')}</h2>`;
        if (/^[-*]\s/.test(l)) return `<li>${l.replace(/^[-*]\s/, '')}</li>`;
        return `<p>${l}</p>`;
      });
      const li = lines.filter((l) => l.startsWith('<li>'));
      return li.length ? `<ul>${li.join('')}</ul>` : lines.join('');
    })
    .join('');
  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(doc.title)}</title>
<style>body{font-family:Georgia,'Times New Roman',serif;max-width:720px;margin:0 auto;padding:40px 20px;color:#1a1d29;line-height:1.7}h1{font-size:30px;margin-bottom:6px}h2{font-size:20px;margin:18px 0 6px}.meta{color:#8a8fa3;font-size:13px;margin-bottom:26px}p{margin:10px 0}ul{margin:10px 0;padding-left:22px}li{margin:4px 0}</style></head>
<body><h1>${esc(doc.title)}</h1><div class="meta">${esc(doc.at || '')} · built by the CRM AI agent</div>${body}</body></html>`;
}

/* ── The build_website tool ───────────────────────────────────────── */

export async function buildWebsite(env, store, user, args, origin = '') {
  const kind = SITE_KINDS.includes(String(args.kind)) ? String(args.kind) : 'landing';
  const title = String(args.title || '').trim().slice(0, 120) || `${kind} page`;
  const brief = String(args.brief || args.instruction || '').trim().slice(0, 4000);
  if (brief.length < 12) {
    return { ok: false, error: 'brief is too short — describe what the site is for, its audience and the key message.' };
  }

  const profile = store ? await getBusinessProfile(store).catch(() => null) : null;
  const brand = brandFor(env, profile);
  brand.profile = profile;

  // Resolve style hints: explicit args.style, else the profile's default.
  const style = String(args.style || profile?.default_style || '').trim();

  let html = '';
  let builder = 'ai';
  try {
    const prompt = [
      { role: 'system', content: siteSystemPrompt(brand, kind) },
      { role: 'user', content: `TITLE: ${title}\nBRIEF: ${brief}${style ? `\nSTYLE HINT: ${style}` : ''}\nProduce the complete single-file HTML now.` },
    ];
    html = await sarvamChat(env, prompt, { maxTokens: 4096, temperature: 0.55 });
    if (!/<!doctype html|<html[\s>]/i.test(html) || html.length < 500) throw new Error('AI output was not an HTML document');
  } catch (e) {
    console.warn('[builder] AI path failed, using signature builder:', e?.message || e);
    html = signatureSite({ title, brief, cta_text: args.cta_text, cta_url: args.cta_url, contact_email: args.contact_email }, brand, kind);
    builder = 'signature';
  }

  html = sanitizeSiteHtml(html);
  if (html.length > MAX_SITE_BYTES) html = html.slice(0, MAX_SITE_BYTES) + '\n<!-- truncated -->';

  const id = `s_${Date.now().toString(36)}${Math.floor(Math.random() * 46656).toString(36)}`;
  const key = `sites/${id}.html`;
  const stored = await env.MEDIA.put(key, html, {
    httpMetadata: { contentType: 'text/html; charset=utf-8' },
    customMetadata: { builtBy: user?.uid || 'agent', kind, title },
  });
  if (!stored) console.warn('[builder] R2 put returned falsy for', key); // record stays the source of truth

  const finalUrl = origin ? `${origin}/sites/${id}` : `/sites/${id}`;

  await putArtifact(store, user?.uid || '', {
    id, kind, title, url: finalUrl, builder, bytes: html.length,
    at: new Date().toISOString(), by: user?.displayName || 'agent',
  });

  return {
    ok: true,
    artifact_id: id,
    kind,
    title,
    url: finalUrl,
    builder,
    bytes: html.length,
    note: `"${title}" is LIVE at ${finalUrl} — share this link with anyone.`,
  };
}

/* ── Public serving (index.js hands over /sites/* here) ───────────── */

export async function serveAgentSite(_request, env, path) {
  const id = String(path.split('/')[2] || '');
  if (!/^[a-z0-9_]+$/i.test(id)) return new Response('bad artifact id', { status: 400 });

  // Sites live in R2…
  const obj = env.MEDIA ? await env.MEDIA.get(`sites/${id}.html`).catch(() => null) : null;
  if (obj) {
    const headers = new Headers({ 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
    obj.writeHttpMetadata(headers);
    return new Response(obj.body, { headers });
  }

  // …notes live in the state store.
  const store = env.DB || env.NEBULA_EMAIL_KV ? (await import('./state.js')).createStore(env) : null;
  if (store) {
    const doc = safeParse(await store.get(`agent:artifact:${id}`));
    if (doc && doc.kind === 'note') {
      return new Response(noteToHtml(doc), { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' } });
    }
  }
  return new Response(notFoundPage(), { status: 404, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
}

function safeParse(raw) {
  try { return JSON.parse(raw); } catch { return null; }
}

function notFoundPage() {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Not found</title></head>
<body style="font-family:sans-serif;text-align:center;padding:60px 20px;color:#333">
<h1>404</h1><p>This page does not exist (or was never built).</p></body></html>`;
}
