// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, public_member_api_docs

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the current platform.
///
/// Wired to the live Firebase project `nebula-crm-70f58`.
/// Re-run `flutterfire configure` to regenerate this file from your local CLI.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Re-run flutterfire configure and replace this file.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFw7TrlgwwKsivkcv_lEOwHutWpRcDYc',
    appId: '1:972178938095:web:b5f07686811d4583cfa31a',
    messagingSenderId: '972178938095',
    projectId: 'nebula-crm-70f58',
    authDomain: 'nebula-crm-70f58.firebaseapp.com',
    storageBucket: 'nebula-crm-70f58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmI0s71dkSfGrDo2mOrmgCUXk8UUYK2Fs',
    appId: '1:972178938095:android:8096a3ac04c2b96ecfa31a',
    messagingSenderId: '972178938095',
    projectId: 'nebula-crm-70f58',
    storageBucket: 'nebula-crm-70f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmI0s71dkSfGrDo2mOrmgCUXk8UUYK2Fs',
    appId: '1:972178938095:ios:placeholder',
    messagingSenderId: '972178938095',
    projectId: 'nebula-crm-70f58',
    storageBucket: 'nebula-crm-70f58.firebasestorage.app',
    iosBundleId: 'com.nebula.nebulaCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmI0s71dkSfGrDo2mOrmgCUXk8UUYK2Fs',
    appId: '1:972178938095:macos:placeholder',
    messagingSenderId: '972178938095',
    projectId: 'nebula-crm-70f58',
    storageBucket: 'nebula-crm-70f58.firebasestorage.app',
    iosBundleId: 'com.nebula.nebulaCrm',
  );
}
