// File generated by FlutterFire CLI. Replace with your own Firebase project config.
// ignore_for_file: lines_longer_than_80_chars, public_member_api_docs

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the current platform.
///
/// Replace the placeholder values below with the values from your
/// Firebase project (run `flutterfire configure` to regenerate this file).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Re-run flutterfire configure and replace this file.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PLACEHOLDER_WEB_API_KEY',
    appId: '1:000000000000:web:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'nebula-crm-placeholder',
    authDomain: 'nebula-crm-placeholder.firebaseapp.com',
    storageBucket: 'nebula-crm-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER_ANDROID_API_KEY',
    appId: '1:000000000000:android:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'nebula-crm-placeholder',
    storageBucket: 'nebula-crm-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER_IOS_API_KEY',
    appId: '1:000000000000:ios:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'nebula-crm-placeholder',
    storageBucket: 'nebula-crm-placeholder.appspot.com',
    iosBundleId: 'com.nebula.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'PLACEHOLDER_MACOS_API_KEY',
    appId: '1:000000000000:macos:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'nebula-crm-placeholder',
    storageBucket: 'nebula-crm-placeholder.appspot.com',
    iosBundleId: 'com.nebula.crm',
  );
}
